apiVersion: apps/v1
kind: Deployment
metadata:
  name: appian-web
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      run: appian-web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: appian-web
    spec:
      containers:
      - image: registry.hub.docker.com/tengland/shared:appian-web
        imagePullPolicy: Always
        name: appian-web
        ports:
        - containerPort: 3000
          protocol: TCP
        command: ["npm", "start"]
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 1
          timeoutSeconds: 10
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
